bdz_project/bdz_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls'))
]

bdz_project/client/urls.py
from django.urls import path

from . import views

app_name = 'client'

urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.authenticate_user, name='auth'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('buy-ticket/', views.BuyTicketView.as_view(), name='buyticket'),
    path('buy/', views.buy_ticket, name='buy'),
    path('ticket-create/', views.ticket_create, name='ticket-create'),
    path('change-credentials/', views.ChangeCredsView.as_view(), name='change-credentials'),
    path('change/', views.change_credentials, name='change'),
    path('change-successful/', views.change_successful, name='change-successful'),
]

bdz_project/client/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings


class Train(models.Model):
    train_number = models.PositiveSmallIntegerField(default=0)
    train_type = models.CharField(max_length=10)

    def __str__(self):
        return self.train_type + ' ' + str(self.train_number)


class Station(models.Model):
    station_name = models.CharField(max_length=20)
    location = models.CharField(max_length=50)

    def __str__(self):
        return self.station_name


class Schedule(models.Model):
    train_id = models.ForeignKey(
        Train,
        default=None,
        on_delete=models.CASCADE
    )

    week_days = models.PositiveSmallIntegerField(default=127)
    valid_from = models.DateField('valid from', default=None)
    valid_until = models.DateField('valid until', default=None, null=True)

    def __str__(self):
        return str(self.train_id)


class TrainStop(models.Model):
    schedule_id = models.ForeignKey(
        Schedule,
        default=None,
        on_delete=models.CASCADE
    )

    station_id = models.ForeignKey(
        Station,
        default=None,
        on_delete=models.CASCADE
    )

    departure_time = models.TimeField(
        'departure time',
        default=None,
        null=True,
        blank=True
    )

    arrival_time = models.TimeField(
        'arrival time',
        default=None,
        null=True,
        blank=True
    )

    def __str__(self):
        if self.departure_time is None:
            return (str(self.schedule_id) + ": " + str(self.station_id.station_name) +
                    "\n-> Arrival: " + str(self.arrival_time))

        if self.arrival_time is None:
            return (str(self.schedule_id) + ": " + str(self.station_id.station_name) +
                    "\n-> Departure: " + str(self.departure_time))

        return (str(self.schedule_id) + ": " + 
                str(self.station_id.station_name) + "\n-> Departure: " +
                str(self.departure_time) + "\n-> Arrival:  " + str(self.arrival_time))


class TicketType(models.Model):
    ticket_type = models.CharField(max_length=20)
    price = models.FloatField(default=0.0)

    def __str__(self):
        return self.ticket_type


class Ticket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, default=None, on_delete=models.CASCADE)
    ticket_type = models.ForeignKey(
        TicketType,
        default=None,
        on_delete=models.CASCADE
    )

    departure_date = models.DateField('departure date', default=None, null=True)
    created_date = models.DateTimeField('created date', default=timezone.now)

    def __str__(self):
        return "Ticket id: " + str(self.pk)


class Route(models.Model):
    starting_station = models.ForeignKey(
        Station,
        related_name='start_station',
        default=None,
        on_delete=models.CASCADE
    )

    end_station = models.ForeignKey(
        Station,
        related_name='end_station',
        default=None,
        on_delete=models.CASCADE
    )

    departure_date = models.TimeField('departure date', default=None)
    arrival_date = models.TimeField('arrival date', default=None)
    duration = models.TimeField('duration', default=None)

    train = models.ForeignKey(
        Train,
        default=None,
        on_delete=models.CASCADE
    )

    ticket = models.ForeignKey(
        Ticket,
        default=None,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.starting_station.station_name) + " -> " + str(self.end_station.station_name)


class Discount(models.Model):
    ticket_type_id = models.ForeignKey(
        TicketType,
        default=None,
        on_delete=models.CASCADE
    )
    discount = models.FloatField(default=0.0)

    def __str__(self):
        return self.ticket_type_id.ticket_type + ' ticket\' s price = -' + (self.discount * 100) + '%'

bdz_project/client/forms.py
import datetime
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from .models import Station

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Enter your username:',
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

    password = forms.CharField(
        label='Enter your password:',
        max_length=30,
        min_length=8,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
    )


class RegisterForm(forms.Form):
    first_name = forms.CharField(
        label='Enter your first name',
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

    last_name = forms.CharField(
        label='Enter your last name',
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

    username = forms.CharField(
        label='Enter your username',
        max_length=20,
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

    email = forms.EmailField(
        label='Enter your email',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )

    password = forms.CharField(
        label='Enter your password',
        max_length=30,
        min_length=8,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
    )

    conf_password = forms.CharField(
        label='Confirm your password',
        max_length=30,
        min_length=8,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if username is None or username == '':
            raise forms.ValidationError('Username cannot be empty')

        username_check = User.objects.filter(username=username)

        if username_check.count():
            raise forms.ValidationError('Username already exists')

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email is None or email == '':
            raise forms.ValidationError('Email cannot be empty')

        password = User.objects.filter(email=email)

        if password.count():
            raise forms.ValidationError('Email already exists')

        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')

        if password is None or password == '':
            raise forms.ValidationError('Password cannot be empty')

        return password

    def clean_conf_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('conf_password')

        if password2 is None or password2 == '':
            raise forms.ValidationError('Confirm password cannot be empty')

        if password1 != password2:
            raise forms.ValidationError('Passwords do not match')

        return password2

    def save(self):
        user = User.objects.create_user(
            self.cleaned_data.get('username'),
            self.cleaned_data.get('email'),
            self.cleaned_data.get('password')
        )

        return user


class RouteForm(forms.Form):
    departure_date = forms.DateField(
        label='Choose a departure date',
        initial=datetime.date.today().strftime('%d.%m.%Y'),
        input_formats=['%d.%m.%Y'],
        widget=forms.DateInput(
            attrs={'class': 'date-picker', 'autocomplete': 'off'}),
        required=False
    )

    departure_station = forms.ModelChoiceField(
        label='Choose a departure station',
        queryset=Station.objects.order_by('station_name').all(),
        required=False
    )

    destination = forms.ModelChoiceField(
        label='Choose a destination',
        queryset=Station.objects.order_by('station_name').all(),
        required=False
    )

    def clean_departure_date(self):
        departure_date = self.cleaned_data.get('departure_date')

        if departure_date is None:
            raise forms.ValidationError('You must pick a departure date')

        curr_date = datetime.date.today()

        if departure_date < curr_date:
            raise forms.ValidationError('Departure date cannot be in the past')

        return departure_date

    def clean_departure_station(self):
        departure_station = self.cleaned_data.get('departure_station')

        if departure_station is None:
            raise forms.ValidationError('You must pick a departure station')

        return departure_station

    def clean_destination(self):
        destination = self.cleaned_data.get('destination')

        if destination is None:
            raise forms.ValidationError('You must pick a destination')

        return destination


class ChangeCredentialsForm(forms.Form):
    curr_password = forms.CharField(
        label='Enter your current password',
        max_length=30,
        min_length=8,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
    )

    new_password = forms.CharField(
        label='Enter your new password',
        max_length=30,
        min_length=8,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.user = self.request.user
        super(ChangeCredentialsForm, self).__init__(*args, **kwargs)

    def clean_curr_password(self):
        curr_password = self.cleaned_data.get('curr_password')

        if curr_password != "":
            tmp_user = authenticate(
                username=self.user.username, password=curr_password)

            if tmp_user is None:
                raise forms.ValidationError('Invalid password')

        return curr_password

    def clean_new_password(self):
        curr_password = self.cleaned_data.get('curr_password')

        if curr_password != "":
            new_password = self.cleaned_data.get('new_password')

            if new_password == curr_password:
                raise forms.ValidationError('New password must be different')

        return curr_password


class TicketInfoForm(forms.Form):
    train = forms.CharField(
        max_length=10,
        required=True
    )

    departure = forms.IntegerField(
        required=True
    )

    arrival = forms.IntegerField(
        required=True
    )

    departure_time = forms.TimeField(
        required=True
    )

    arrival_time = forms.TimeField(
        required=True
    )

    departure_date = forms.DateField(
        required=True
    )

bdz_project/client/templates/client/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com/%22%3E">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
  media="all">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<link rel="stylesheet" href="{% static 'client/css/all.css' %}">
<link rel="stylesheet" href="{% static 'client/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'client/css/register-styles.css' %}">
<link rel="stylesheet" href="{% static 'client/css/trainChoice-styles.css' %}">
<link rel="stylesheet" href="{% static 'client/css/ticketIssue-styles.css' %}">

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} Home {% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Image and text -->
      <a id="brand" class="nav-item" href="{% url 'client:index' %}">
        <div class="inner2">
          <img src="{% static 'client/images/logobdz2.png' %}" class="d-inline-block align-top">
        </div>
      </a>
      
      <ul class="navbar-nav ml-4 mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'client:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a id="ticket-link" class="nav-link" href="{% url 'client:buyticket' %}">Buy a ticket</a>
        </li>
        <li class="nav-item">
          <img src="{% static 'client/images/Buy_a_ticket_button_anim_final.gif' %}" alt="gif preset" class="gif-file">
        </li>
      </ul>

      {% if request.user.is_authenticated %}
      <div class="form-inline my-2 my-lg-0 mr-sm-3 greeting navbar-nav">
        <a href="{% url 'client:change-credentials' %}" class="nav-link" type="Sign up">Wellcome, {{ request.user.username }}!</a>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <a href="{% url 'client:logout' %}" class="btn btn-danger my-2 my-sm-0" type="Log out">Log out</a>
      </div>
      {% else %}
      <div class="form-inline my-2 my-lg-0 mr-sm-3">
        <a href="{% url 'client:register' %}" class="btn btn-danger my-2 my-sm-0" type="Sign up">Sign up</a>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <a href="{% url 'client:login' %}" class="btn btn-danger my-2 my-sm-0" type="Sign in">Sign in</a>
      </div>
      {% endif %}
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</body>

<script>
  $("#ticket-link").hover(function() {
  $('.gif-file').toggle();
});
</script>
</html>

bdz_project/client/templates/client/changeCredentials.html
{% extends "client/base.html" %}
{% block title %} Change credentials {% endblock %}
{% block content %}
{% load static %}

<form class="needs-validation" action="{% url 'client:change' %}" method="POST">
    {% csrf_token %}

    <div class="form-group col-md-4 mb-3">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}

        <script type=text/javascript>toastr["error"]("{{ error }}", "" ); </script>
        
        {% endfor %}
        {% endfor %}
        {% endif %}
        
        {% for field in form %} 
        <div>
            {{ field.label_tag }}
            <div class="mb-3">
                {{ field }}
            </div>
        </div>
        {% endfor %}
        
        <button class="btn btn-danger my-2 my-sm-0" type="submit">Next</button>
    </div>
   
</form>

{% endblock %}

bdz_project/client/templates/client/changeSuccessful.html
{% extends "client/base.html" %}
{% block title %} Change success {% endblock %}
{% block content %}
{% load static %}

<div class="text-center h-50 mt-5">
    <p>Successfuly changed credentials</p>
    <a href="{% url 'client:index' %}" class="btn btn-danger my-2 my-sm-0">Reurn home</a>
</div>

{% endblock %}

bdz_project/client/templates/client/index.html
{% extends "client/base.html" %}
{% load static %}
{% block content %}
<div class="mb-5">
<div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>

  </ol>

  <div class="carousel-inner">
    <div id="citem1" class="carousel-item active" data-interval="2000">
      <img class="d-block w-100" src="{% static 'client/images/test2.jpg' %}">
      <div class="container"></div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'client/images/test.jpg' %}">
      <div class="container">

      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'client/images/cardimage1.jpg' %}">
      <div class="container">

      </div>
    </div>
  </div>
  <a href="#myCarousel" class="carousel-control-prev" role="button" data-slide="prev">
    <span class="sr-only">Previous</span>
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  </a>
  <a href="#myCarousel" class="carousel-control-next" role="button" data-slide="next">
    <span class="sr-only">Next</span>
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
  </a>
</div>
</div>
<!--
<div class  = "card">
  <div class="rowjustify-content-center">
    
      <div class="card shadow" style="width: 30rem;">
        <div class="inner">
          <img class="card-img-top" src="{% static 'client/images/cardimage1.jpg' %}">
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">wtf be marto</p>
          <a href="{% url 'client:index' %}" class="btn btn-danger">Go somewhere</a>
        
      </div>
    </div>
  </div>
  <div class  = "card">
    
      <div class="card shadow" style="width: 30rem;">
        <div class="inner">
          <img class="card-img-top" src="{% static 'client/images/cardimage2.jpg' %}">
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">wtf be marto</p>
          <a href="{% url 'client:index' %}" class="btn btn-danger">Go somewhere</a>
        
      </div>
    </div>
  </div>
  <div class  = "card">
    
      <div class="card shadow" style="width: 30rem;">
        <div class="inner">
          <img class="card-img-top" src="{% static 'client/images/cardimage3.jpg' %}">
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">wtf be marto</p>
          <a href="{% url 'client:index' %}" class="btn btn-danger">Go somewhere</a>
         
        </div>
      </div>
    </div>
  </div>
-->
<div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
  <div class="col">
    <div class="card">
      <!--<div class="card shadow">-->
        <div class="inner">
          <img src="{% static 'client/images/cardimage1.jpg' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">Buy a ticket!</h5>
          <p class="card-text"></p>
        </div>
      <!--</div>-->
    </div>
  </div>

  <div class="col">
    <div class="card">
      <!--<div class="card shadow">-->
        <div class="inner">
          <img src="{% static 'client/images/cardimage2.jpg' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">Enjoy your trip!</h5>
          <p class="card-text"></p>
        </div>
      <!--</div>-->
    </div>
  </div>
  <div class="col">
    <div class="card">
      <!--<div class="card shadow">-->
        <div class="inner">
          <img src="{% static 'client/images/cardimage3small.jpg' %}" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">Tickets for people of all ages!</h5>
          <p class="card-text">We have a wide variety of tickets for every single age group, no discrimination and lower prices!</p>
        </div>
      <!--</div>-->
    </div>
  </div>
</div>

<script type=text/javascript>
  toastr.options = {
    "closeButton": false,
    "debug": false,
    "newestOnTop": false,
    "progressBar": false,
    "positionClass": "toast-top-center",
    "preventDuplicates": false,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "5000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  }

  toastr["info"]("Този сайт използва куки");
</script> 

{% endblock %}

bdz_project/client/templates/client/login.html
{% extends "client/base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'client/css/login-style.css' %}">

<form action="{% url 'client:auth' %}" method="POST" id="signInForm">
  {% csrf_token %}

  <input type="hidden" name="next" id="id_next" value="{{ request.GET.next }}"/>
  <img src="{% static 'client/images/register_login-backgroundimage2.jpg' %}" class="img-fluid w-100" alt="Responsive image">

<div class="card" id="login-card">
  <div class="card-body">
  <div class="shadow-lg p-1 mb-5 bg-white rounded">
    <h5 class="card-title">Sign in</h5>

  {% if form.errors %}
    <script type=text/javascript>toastr["error"]("The email or password you entered is incorrect", "Invalid credentials")</script>
  {% endif %}

  <div class="form-group col-md-4 mb-3">

    {% for field in form %}
    <div>
      <label class="login-label" for="{{ field.auto_id }}">{{ field.label }}</label>
      
      {{ field }}

    </div>
    {% endfor %}

    <div class="login-button">
      <button class="btn btn-danger my-2 my-sm-0" type="submit">Submit</button>
    </div>

  </div>
</form>

</div>
</div>

{% endblock %}

bdz_project/client/templates/client/product.html
{% extends "client/base.html" %}
{% block title %} Buy ticket {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'client/css/product-styles.css' %}">

<form class="needs-validation" action="{% url 'client:buy' %}" method="POST">
    {% csrf_token %}

    
    <img src="{% static 'client/images/product-image2.jpg' %}" class="img-fluid w-100" alt="Responsive image">
    <img src="{% static 'client/images/bdz-bilet.jpg' %}" alt="Responsive image" class="img-thumbnail" id="product-thumbnailImage">
    
    <div class="card" id="product-card">
        <div class="card-body">
            <h5 class="card-title" id="product-card-title">Enter the details for your purchase</h5>
            <div class="form-group col-md-4 mb-3">
                
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                    <script type=text/javascript>toastr["error"]("{{ error }}", "Invalid choice" ); </script> 
                {% endfor %}
                {% endfor %}
                {% endif %}
        
        <div>
            <div class="mb-3">    
                {% for field in form %} 
                <div>
                    <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Next</button>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    $('.date-picker').datepicker({
        todayHighlight: true,
        autoclose: true,
        dateFormat: 'dd.mm.yy',
    });
    
    $('.time-picker').timepicker({
        timeFormat: 'HH:mm',
        interval: 60,
        minTime: '8',
        maxTime: '20:00',
        startTime: '8:00',
        dynamic: false,
        dropdown: true,
        scrollbar: false
    });

</script>

<!--<script>
    
    var thumbnailImage = document.getElementById('product-thumbnailImage');
    var x = 0;
    var n = new Boolean(true);

    if($(thumbnailImage).hover(function() { $('.img-thumbnail').toggle(); }) == n) {
        
        setInterval(function(){thumbnailImage.style.right = x + "px"; x++; }, 20);
    }

</script> -->
{% endblock %}

bdz_project/client/templates/client/trainChoice.html
{% extends "client/base.html" %}
{% block title %} Train choice {% endblock %}
{% block content %}
{% load static %}

<form action="{% url 'client:ticket-create' %}" method="POST">
{% csrf_token %}

    <input type="hidden" name="train" id="id_train"/>
    <input type="hidden" name="departure" id="id_departure"/>
    <input type="hidden" name="arrival" id="id_arrival"/>
    <input type="hidden" name="departure_time" id="id_departure_time"/>
    <input type="hidden" name="arrival_time" id="id_arrival_time"/>
    <input type="hidden" name="departure_date" id="id_departure_date" value="{{ departure_date|date:"Y-m-d" }}"/>

    
    
    <img src="{% static 'client/images/choiceTrain2.jpg' %}" class="img-fluid w-100" alt="Responsive image">

    <div class="card w-80" id="trainChoice-card">
  <div class="card-body">
  <div class="shadow-lg p-1 mb-5 bg-white rounded">
    {% for row in rows %}
    <div
        data-trainId="{{ row.2 }}"
        data-departureId="{{ row.0 }}"
        data-arrivalId="{{ row.1 }}"
        data-departureTime="{{ row.6|time:"H:i" }}"
        data-arrivalTime="{{ row.7|time:"H:i" }}"
    >
  <table class="table">
  <thead class="thead-light">
    <tr>
        <th>Train</th>
        <th>Departure</th>
        <th>Arrival</th>
        <th>Duration</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{ row.5 }}</td>
        <td>{{ row.6|time:"H:i" }}</td>
        <td>{{ row.7|time:"H:i" }}</td>
        <td>{{ row.8 }}</td>
    </tr>
  </tbody>
</table>
    <button class="btn btn-danger my-2 my-sm-0 choose" type="button">Choose</button>
</div>
    {% endfor %}
</div>
    <button class="btn btn-danger my-2 my-sm-0" type="submit">Submit</button>
</div>

        
    </div>
    

    
</form>


<script>
    $(function() 
    {
        $('.choose').on('click', function(e) 
        {
            e.preventDefault();

            let element = e.target;
            let info = $(element).parent()[0];

            debugger;

            $('#id_train').val($(info).data('trainid'));
            $('#id_departure').val($(info).data('departureid'));
            $('#id_arrival').val($(info).data('arrivalid'));
            $('#id_departure_time').val($(info).data('departuretime'));
            $('#id_arrival_time').val($(info).data('arrivaltime'));
        })
    })
</script>

{% endblock %}